import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Canvas智能助手",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: '/icon/CanvasIcon64x64.ico', sizes: '64x64', type: 'image/x-icon' },
      { url: '/icon/CanvasIcon256x256.ico', sizes: '256x256', type: 'image/x-icon' },
    ],
    apple: '/icon/CanvasEduBotIcon.png',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body 
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <main className="flex-grow">{children}</main>
        <footer className="border-t py-4 px-6 text-center text-sm text-gray-500">
          © 猪头Canvas会不会遇上Agent学姐 | 基于 Canvas 开发
        </footer>
      </body>
    </html>
  );
}